[package]
name = "tauri-app"
version = "1.8.5"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lofty = "0.20"
base64 = "0.22"
walkdir = "2"
tauri-plugin-dialog = "^2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
reqwest = { version = "0.12", features = ["json", "multipart", "stream"] }
futures-util = "0.3"
zip = { version = "2", default-features = false, features = ["deflate"] }
rusqlite = { version = "0.32", features = ["bundled"] }
tokio = { version = "1", features = ["net", "rt-multi-thread", "io-util", "sync"] }
chrono = "0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
